name: CI

on:
- pull_request
- push

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
      if: matrix.os == 'windows-latest'

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - run: yarn hygen:build -- init self
    - run: yarn test
